# Generated by Django 3.2.5 on 2022-06-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220623_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
    ]
